name: Build do Instalador
on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build do Instalador Inno
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calcular versão
        id: calcular_versao
        run: |
          $date = Get-Date -Format 'yyyyMMdd'
          $increment = ${{ github.run_number }}
          $version = "$date.$increment"
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      # - name: Compilar Instalador Inno
      #   uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      #   with:
      #     path: ./ScriptDoInstalador.iss
      #     options: /O+ /dVersao="${{ env.VERSION }}"

      - name: Criar release no GitHub
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Sky Digitaliza - Desktop v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          # artifacts: D:\a\SkyDigitalliza.Desktop\SkyDigitalliza.Desktop\Instalador\SkyDigitalliza.Desktop.Instalador.exe
          # artifactContentType: application/octet-stream
          makeLatest: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
