name: Build do Instalador
on:
  push:
    branches:
      - "main"
    paths: 
      - 'Binários/monitor/**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build do Instalador Inno
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calcular versão
        id: calcular_versao
        run: |
          $date = Get-Date -Format 'yyyyMMdd'
          $increment = ${{ github.run_number }}
          $version = "$date.$increment"
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Criar release no GitHub
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Sky Digitaliza - Desktop v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          makeLatest: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
